# frozen_string_literal: true
require 'rdf'
require 'rdf/rdfxml'
require 'rdf/turtle'
require_relative 'graph_builder'
require_relative 'carpedia_graph'
include RDF
include GraphBuilder

CarpediaGraph
    .with_class('Car')
    .with_class('Body')
    .with_class('ElectricalSupplySystem')
    .with_class('Gauge')
    .with_class('IgnitionSystem')
    .with_class('LightingSystem')
    .with_class('StartingSystem')
    .with_class('BrakingSystem')
    .with_class('Sensor')
    .with_class('Engine')
    .with_class('EngineCoolingSystem')
    .with_class('EngineOilSystem')
    .with_class('ExhaustSystem')
    .with_class('FuelSupplySystem')
    .with_class('SuspensionSystem')
    .with_class('SteeringSystem')
    .with_class('TransmissionSystem')
    .with_class('Hood')
    .with_class('Bumper')
    .with_class('Door')
    .with_class('Window')
    .with_class('Windshield')
    .with_class('Roof')
    .with_class('Trunk')
    .with_class('Fender')
    .with_class('Battery')
    .with_class('Alternator')
    .with_class('VoltageRegulator')
    .with_class('FuelGauge')
    .with_class('Speedometer')
    .with_class('Tachometer')
    .with_class('Odometer')
    .with_class('OilPressureGauge')
    .with_class('TemperatureGauge')
    .with_class('Ammeter')
    .with_class('Voltmeter')
    .with_class('Dynamometer')
    .with_class('Manometer')
    .with_class('Clinometer')
    .with_class('Hydrometer')
    .with_class('WaterTemperatureGauge')
    .with_class('SparkingCable')
    .with_class('Distributor')
    .with_class('IgnitionCoil')
    .with_class('IgnitionBox')
    .with_class('IgnitionMagneto')
    .with_class('SparkPlug')
    .with_class('GlowPlug')
    .with_class('Headlight')
    .with_class('TailLight')
    .with_class('FogLight')
    .with_class('TurnSignalLight')
    .with_class('BrakeLight')
    .with_class('StarterMotor')
    .with_class('StarterSolenoid')
    .with_class('StarterDrive')
    .with_class('StarterRelay')
    .with_class('ABS')
    .with_class('AdjustingMechanism')
    .with_class('Anchor')
    .with_class('BleedNipple')
    .with_class('BrakeBackingPlate')
    .with_class('BrakeBackingPad')
    .with_class('BrakeCoolingDuct')
    .with_class('BrakeDisc')
    .with_class('BrakeFluid')
    .with_class('BrakeDrum')
    .with_class('BrakeLining')
    .with_class('BrakePad')
    .with_class('BrakePedal')
    .with_class('BrakePiston')
    .with_class('BrakePump')
    .with_class('BrakeRoll')
    .with_class('BrakeRotor')
    .with_class('BrakeServo')
    .with_class('BrakeShoe')
    .with_class('BrakeWarningLight')
    .with_class('CalibratedFrictionBrake')
    .with_class('Caliper')
    .with_class('CombinationValve')
    .with_class('DualCircuitBrakeSystem')
    .with_class('HoldDownSprings')
    .with_class('Hose')
    .with_class('HydraulicBoosterUnit')
    .with_class('LoadSensingValve')
    .with_class('MasterCylinder')
    .with_class('MeteringValve')
    .with_class('Handle')
    .with_class('PressureDifferentialValve')
    .with_class('ProportioningValve')
    .with_class('Reservoir')
    .with_class('ShoeReturnSpring')
    .with_class('Tyre')
    .with_class('VacuumBrakeBooster')
    .with_class('WheelCylinder')
    .with_class('WheelStud')
    .with_class('AirbagSensor')
    .with_class('ABSSensor')
    .with_class('BrakeSensor')
    .with_class('CamshaftPositionSensor')
    .with_class('CoolantTemperatureSensor')
    .with_class('CrankshaftPositionSensor')
    .with_class('FuelLevelSensor')
    .with_class('AccessoryBelt')
    .with_class('AirDuct')
    .with_class('AirFilter')
    .with_class('AirIntakeHose')
    .with_class('IntakeManifold')
    .with_class('Camshaft')
    .with_class('ConnectingRod')
    .with_class('CrankCase')
    .with_class('Crankshaft')
    .with_class('CrankPulley')
    .with_class('CylinderHead')
    .with_class('Distributor')
    .with_class('DriveBelt')
    .with_class('EngineBlock')
    .with_class('EngineCradle')
    .with_class('EngineValve')
    .with_class('Piston')
    .with_class('StarterMotor')
    .with_class('TimingBelt')
    .with_class('AirBlower')
    .with_class('CoolantHose')
    .with_class('CoolingFan')
    .with_class('FanBlade')
    .with_class('FanBelt')
    .with_class('FanClutch')
    .with_class('Radiator')
    .with_class('WaterNeck')
    .with_class('WaterPipe')
    .with_class('WaterPump')
    .with_class('WaterPumpGasket')
    .with_class('WaterTank')
    .with_class('OilFilter')
    .with_class('OilPump')
    .with_class('OilTank')
    .with_class('OilGasket')
    .with_class('CatalyticConverter')
    .with_class('ExhaustClamp')
    .with_class('ExhaustFlangeGasket')
    .with_class('ExhaustGasket')
    .with_class('ExhaustManifold')
    .with_class('ExhaustManifoldGasket')
    .with_class('ExhaustPipe')
    .with_class('HeatShield')
    .with_class('HeatSleeving')
    .with_class('Resonator')
    .with_class('Muffler')
    .with_class('SpacerRing')
    .with_class('AirFilter')
    .with_class('Carburetor')
    .with_class('ChokeCable')
    .with_class('ExhaustGasRecirculationValve')
    .with_class('FuelCap')
    .with_class('FuelCell')
    .with_class('FuelCooler')
    .with_class('FuelDistributor')
    .with_class('FuelFilter')
    .with_class('FuelFilterSeal')
    .with_class('FuelInjector')
    .with_class('FuelInjectorNozzle')
    .with_class('FuelLine')
    .with_class('FuelPump')
    .with_class('FuelPumpGasket')
    .with_class('FuelPressureRegulator')
    .with_class('FuelRail')
    .with_class('FuelTank')
    .with_class('FuelWaterSeparator')
    .with_class('IntakeManifold')
    .with_class('IntakeManifoldGasket')
    .with_class('ThrottleBody')
    .with_subclass('FuelGauge', 'Gauge')
    .with_subclass('Speedometer', 'Gauge')
    .with_subclass('Tachometer', 'Gauge')
    .with_subclass('Odometer', 'Gauge')
    .with_subclass('OilPressureGauge', 'Gauge')
    .with_subclass('TemperatureGauge', 'Gauge')
    .with_subclass('Ammeter', 'Gauge')
    .with_subclass('Voltmeter', 'Gauge')
    .with_subclass('Dynamometer', 'Gauge')
    .with_subclass('Manometer', 'Gauge')
    .with_subclass('Clinometer', 'Gauge')
    .with_subclass('Hydrometer', 'Gauge')
    .with_subclass('WaterTemperatureGauge', 'Gauge')
    .with_subclass('AirbagSensor', 'Sensor')
    .with_subclass('ABSSensor', 'Sensor')
    .with_subclass('BrakeSensor', 'Sensor')
    .with_subclass('CamshaftPositionSensor', 'Sensor')
    .with_subclass('CoolantTemperatureSensor', 'Sensor')
    .with_subclass('CrankshaftPositionSensor', 'Sensor')
    .with_subclass('FuelLevelSensor', 'Sensor')
